[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
plotters = "0.3.3"
rand = "0.8.5"
tqdm = "0.6.0"

[dev-dependencies]
mockall = "0.11.4"
